steps:
  - label: "fossa analyze"
    agents:
      queue: "init"
      docker: "*"
    command: ".buildkite/scripts/fossa.sh"
  - label: ":java: Unit test with test services"
    agents:
      queue: "workers"
      docker: "*"
    command: "./gradlew --no-daemon test"
    timeout_in_minutes: 15
    retry:
      automatic:
        - exit_status: "*"
          limit: 3
    plugins:
      - docker-compose#v3.0.0:
          run: unit-test-test-service
          config: docker/buildkite/docker-compose.yaml

  - label: ":java: Unit test with docker services sticky on"
    agents:
      queue: "workers"
      docker: "*"
    command: "./gradlew --no-daemon test"
    timeout_in_minutes: 15
    retry:
      automatic:
        - exit_status: "*"
          limit: 3
    plugins:
      - docker-compose#v3.0.0:
          run: unit-test-docker-sticky-on
          config: docker/buildkite/docker-compose.yaml

  - label: ":java: Unit test with docker services sticky off"
    agents:
      queue: "workers"
      docker: "*"
    command: "./gradlew --no-daemon test"
    timeout_in_minutes: 15
    retry:
      automatic:
        - exit_status: "*"
          limit: 3
    plugins:
      - docker-compose#v3.0.0:
          run: unit-test-docker-sticky-off
          config: docker/buildkite/docker-compose.yaml
  - wait
