container:
  kubernetes: &kubernetes
    gitEnvFrom:
      - secretRef:
          name: oss-github-ssh-credentials
    sidecars:
    - image: us-west1-docker.pkg.dev/ci-compute/buildkite-images/buildkite-dind:v1
      volumeMounts:
        - mountPath: /var/run/
          name: docker-sock
      securityContext:
        privileged: true
        allowPrivilegeEscalation: true
    mirrorVolumeMounts: true # CRITICAL: this must be at the same indentation level as sidecars
    podSpec: &podSpec
      containers:
        - &commandContainer
          image: us-west1-docker.pkg.dev/ci-compute/buildkite-images/buildkite-command-container:v2
          command:
          - |-
            echo "Command step was not overridden."
            exit 1
          volumeMounts:
            - mountPath: /var/run/
              name: docker-sock
          resources:
            requests:
              cpu: 7500m
              memory: 30G
      volumes:
      - name: docker-sock
        emptyDir: {}

agents:
  queue: buildkite-gcp

steps:
  - label: "Lint Check"
    plugins:
      - kubernetes:
          <<: *kubernetes
          podSpec:
            <<: *podSpec
            containers:
              - <<: *commandContainer
                command:
                - |-
                  .buildkite/scripts/lint.sh
      - docker-compose#v3.0.0:
          run: unit-test-test-service
          config: docker/buildkite/docker-compose.yaml

  - label: ":java: Unit test with test services"
    artifact_paths:
      - "build/reports/jacoco/test/jacocoTestReport.xml"
      - "build/reports/metadata.txt"
    timeout_in_minutes: 30
    retry:
      automatic:
        - exit_status: "*"
          limit: 3
    plugins:
      - kubernetes:
          <<: *kubernetes
          podSpec:
            <<: *podSpec
            containers:
              - <<: *commandContainer
                command:
                - |-
                  ./gradlew --no-daemon test jacocoTestReport
                  .buildkite/scripts/coverage_metadata.sh build/reports/metadata.txt
      - docker-compose#v3.0.0:
          run: unit-test-test-service
          config: docker/buildkite/docker-compose.yaml

  - label: ":java: Unit test with docker services sticky on"
    timeout_in_minutes: 30
    retry:
      automatic:
        - exit_status: "*"
          limit: 3
    plugins:
      - kubernetes:
          <<: *kubernetes
          podSpec:
            <<: *podSpec
            containers:
              - <<: *commandContainer
                command:
                - |-
                  ./gradlew --no-daemon test
      - docker-compose#v3.0.0:
          run: unit-test-docker-sticky-on
          config: docker/buildkite/docker-compose.yaml

  - label: ":java: Unit test with docker services sticky off"
    timeout_in_minutes: 30
    retry:
      automatic:
        - exit_status: "*"
          limit: 3
    plugins:
      - kubernetes:
          <<: *kubernetes
          podSpec:
            <<: *podSpec
            containers:
              - <<: *commandContainer
                command:
                - |-
                  ./gradlew --no-daemon test
      - docker-compose#v3.0.0:
          run: unit-test-docker-sticky-off
          config: docker/buildkite/docker-compose.yaml
