# Always use a release version or a specific commit hash below. Don't use
# a branch name since we'd keep getting updates as long as there are new
# commits to that branch and one of them can break the build
FROM adoptopenjdk/openjdk11:jdk-11.0.10_9-alpine

RUN mkdir /cadence-java-client
WORKDIR /cadence-java-client
