name: Release to Maven Central

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version to release (if empty, derive from project version)'
        required: false
  # Automatic trigger on pushing a version tag (e.g., "v1.2.3")
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Determine release version
        id: vars
        run: |
          ./gradlew -q printVersion

      - name: Publish to Sonatype OSSRH (Maven Central)
        env:
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          OSSATUBER_PASSWORD: ${{ secrets.OSSATUBER_PASSWORD }}
          OSSATUBER_USERNAME: ${{ secrets.OSSATUBER_USERNAME }}
        run: | # TODO old way of setting the properties from environment variables in gradle
          ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository --info \
           -Psigning.keyId="${SIGNING_KEY_ID}" \
            -Psigning.password="${SIGNING_PASSWORD}" \
            -Psigning.key="${SIGNING_KEY}" \
            -PossrhPassword="${OSSATUBER_PASSWORD}" \
            -PossrhUsername="${OSSATUBER_USERNAME}"
